baseurl = "http://gastaud.io"
languageCode = "fr-fr"
canonifyurls = true
title = "Jean-Yves Gastaud"

[indexes]
   category = "categories"
   tag = "tags"

[Params]
  subtitle = "Mes notes en vrac"
  description = "Un peu de dev Drupal, de devops, "
  AuthorName = "Jean-Yves Gastaud"
  github = "jygastaud"
  twitter = "jygastaud"
  cover = "/images/background-cover.jpg"
  logo = "/img/logo-1.jpg"
  googleAnalytics = true
  disqusShortname = "gastaudio"

[[menu.main]]
    name = "Blog"
    pre = ""
    url = "/article/"
    weight = 1

[[menu.main]]
    name = "Projets / Contributions"
    pre = ""
    url = "/projet/"
    weight = 2

[[menu.footer]]
    name = "RSS"
    pre = ""
    url = "/index.xml"
    weight = 3
