baseurl = "http://gastaud.io"
languageCode = "fr-fr"
canonifyurls = true
title = "Jean-Yves Gastaud"

[indexes]
   category = "categories"
   tag = "tags"

[Params]
  baseurl_prod = "http://gastaud.io/"
  subtitle = "Mes notes en vrac"
  description = "Un peu de dev Drupal, de DevOps, de tout, de rien"
  AuthorName = "Jean-Yves Gastaud"
  github = "jygastaud"
  twitter = "jygastaud"
  cover = "/images/background-cover.jpg"
  logo = "/img/logo-1.jpg"
  googleAnalytics = true
  disqusShortname = "gastaudio"

[[menu.main]]
    name = "Blog"
    pre = ""
    url = "/article/"
    weight = 1

[[menu.main]]
    name = "Projets / Contributions"
    pre = ""
    url = "/projet/"
    weight = 2

#[[menu.main]]
#    name = "Contact"
#    pre = ""
#    url = "/contact/"
#    weight = 4

[[menu.footer]]
    name = "RSS"
    pre = ""
    url = "/index.xml"
    weight = 3

#[[menu.footer]]
#    name = "Contact"
#    pre = ""
#    url = "/contact/"
#    weight = 4
