baseurl = "http://www.gastaud.io"
languageCode = "fr-fr"
canonifyurls = true
title = "JYGastaud"

[indexes]
   category = "categories"
   tag = "tags"
[Params]
  subtitle = "Mes notes en vracs"
  AuthorName = "Jean-Yves Gastaud"
  github = "jygastaud"
  twitter = "jygastaud"
  description = ""
  cover = "/images/background-cover.jpg"
  logo = "/img/logo-1.jpg"

[[menu.main]]
    name = "Accueil"
    pre = ""
    url = "/"
    weight = 0

[[menu.main]]
    name = "Blog"
    pre = ""
    url = "/article"
    weight = 1

[[menu.main]]
    name = "Projets / Contributions"
    pre = ""
    url = "/projet"
    weight = 2

[[menu.main]]
    name = "RSS"
    pre = ""
    url = "/index.xml"
    weight = 3
